name: Pipeline

on: push

jobs:
  build-os:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          chmod +x ./deps-container.sh
          sudo ./deps-container.sh

      - name: Generate Ninja project with CMake
        run: |
          cmake -GNinja -S . -B ./build/

      - name: Compile Kernel
        run: |
          ninja -C build/ kernel
      
      - name: Compile Filesystem/Userland
        run: ninja -C build/ userland

      - name: Build iso image
        run: ninja -C build/ iso
